apiVersion: v1
kind: Service
metadata:
  name: mocklm
  labels:
    app: mocklm
spec:
  selector:
    app: mocklm
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
